# -*- coding: utf-8 -*-
"""NH농협증권빅데이터분석_최종코드_241114.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNUqsFRMoXo0qgCMfKOMzP6BBdoJ_-9R

# <뉴스로 뽑은 etf 추천 큐레이션 서비스>
- 1단계: AI를 통해 특정 주제와 관련된 뉴스를 찾습니다.
- 2단계: 뽑힌 뉴스와 관련된 산업을 추출하고, 해당 산업군의 주식이나 etf 키워드를 추출합니다.
- 3단계: 주식이 추출된 경우, 해당 주식을 10% 이상 가지고 있는 etf를 다시 추출해 etf 리스트를 만듭니다.
- 4단계:: 이렇게 만들어진 etf 리스트를 몇 가지 기준을 통해 검열합니다.
(기준: 수익성, 안정성, 유동성 등)
- 5단계: 검열된 리스트를 AI에 제공해 최종적으로 적합한 etf를 고객에게 추천합니다.

## 1. 데이터 다운로드
"""

# 필요한 모듈 import
import pandas as pd

# ETF holdings data
hold=pd.read_csv('NH_CONTEST_DATA_ETF_HOLDINGS.csv', encoding='euc-kr')

# ETF dividend data
div=pd.read_csv('NH_CONTEST_DATA_HISTORICAL_DIVIDEND.csv', encoding='euc-kr')

# ETF 점수 data
score=pd.read_csv('NH_CONTEST_ETF_SOR_IFO.csv', encoding='euc-kr')

# NH 고객보유정보 data
cus=pd.read_csv('NH_CONTEST_NHDATA_CUS_TP_IFO.csv', encoding='euc-kr')

# NH 매수매도계좌정보 data
buysell=pd.read_csv('NH_CONTEST_NHDATA_IFW_OFW_IFO.csv', encoding='euc-kr')

# 주식일별정보 data
stk=pd.read_csv('NH_CONTEST_NHDATA_STK_DD_IFO.csv', encoding='euc-kr')

# 해외종목정보 data
forstk=pd.read_csv('NH_CONTEST_NW_FC_STK_IEM_IFO.csv', encoding='euc-kr')

# 종목일자별시세 data
datepc=pd.read_csv('NH_CONTEST_STK_DT_QUT.csv', encoding='euc-kr')

"""## 2. 뉴스를 통해 etf 선별
- open ai에 뉴스 주제를 입력해서 나온 키워드로 etf를 선별한다.
"""

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, ToolMessage
import yfinance as yf
from langchain_core.prompts import PromptTemplate
import pandas as pd
import numpy as np
import os
import requests
import re
from datetime import datetime
import json
from langchain_core.output_parsers import CommaSeparatedListOutputParser
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Mm
from docxcompose.composer import Composer
from docx import Document
import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Mm
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.pydantic_v1 import BaseModel, Field
from openai import AzureOpenAI
from openai import OpenAI

AZURE_ENDPOINT='Please enter your Azure Endpoint'
AZURE_API_KEY='Please enter your Azure Api Key'
OPENAI_API_KEY = "Please enter your Openai Api Key"
PERPLEXITY_API_KEY ="Please enter your Perplexity Api Key"

"""## 2. 경제지표 뽑기"""

client = OpenAI(api_key=PERPLEXITY_API_KEY, base_url="https://api.perplexity.ai")

class economic_index(BaseModel):
    interest_rate: str = Field(description="explaination about America's intesert rate")
    employment_figures: str = Field(description="explaination about America's employment_figures")
    inflation: str = Field(description="explaination about America's inflation rate")
    sp500: str = Field(description="explaination about S&P500 moving")
    economic_growth: str = Field(description="explaination about economic growth and interest rate policy")

now=datetime.datetime.now()
year=now.strftime('%Y')
month=now.strftime('%m')

index_messages = [
    {
        "role": "system",
        "content": """you are a search helper for analyst. your goal is to find economic index and news that user asks"""
    },
    {
        "role": "user",
        "content": f"find {year}/{month} information about interest rate, employment figures, inflation for America's and S&P500 change. and find news about economic growth and interest policy"
    }
]

response = client.chat.completions.create(
    model="llama-3.1-8b-instruct",
    messages=index_messages,
    temperature=0.7,
    max_tokens=1000
)

perplexity_index_response= response.choices[0].message.content

### azure로 시도
deployment_name = 'gpt-4o-mini'

# Initialize the Azure OpenAI client
client = AzureOpenAI(
        azure_endpoint = AZURE_ENDPOINT,
        api_key=AZURE_API_KEY,
        api_version='2024-02-15-preview',
        )

prompt_template = """
You are an economic analyst. Based on the data I provide, including the U.S. interest rates,
 employment indicators, inflation rate, S&P500 changes, interest rate policies,
and economic growth news, write a report analyzing the current state of each indicator and
the factors influencing their fluctuations.
In case of interest rates, employment indicators, and inflation rate, please get the exact data from FRED website,
which are the latest.
Also, present the impact of these indicators on the U.S. economy and the economic outlook,
include possible scenarios based on changes in economic policies or market conditions. Please answer using Korean.
Get the accurate names of indicators, especially S&P500.

Please provide your answer in the following format:
{format_instructions}

perplexity_ai_response: {perplexity_ai_response}
"""

parser = JsonOutputParser(pydantic_object=economic_index)

response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "json_object" },
    messages=[
        {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
        {
            "role": "user",
            "content": prompt_template.format(
                format_instructions=parser.get_format_instructions(),
                perplexity_ai_response=perplexity_index_response
            )
        }
    ]
)

index_response = response.choices[0].message.content

index_response_json=parser.invoke(index_response)

index_response = index_response.replace("{", "").replace("}", "")

"""## 3. 뉴스 관련 추천 산업 선정 및 문서 작성"""

client = OpenAI(api_key=PERPLEXITY_API_KEY, base_url="https://api.perplexity.ai")

# 원하는 뉴스 주제를 고를 수 있다.
news_topic="Russia-Ukraine War"

news_example="""<기술 산업>
Write a comprehensive analysis of why the technology sector is considered promising for ETF investments. Focus specifically on news and trends from November 2024. The response should include:
Recent government policies supporting technology sectors.
Key areas of innovation such as AI, green technology, and quantum computing.
Economic factors driving investor interest.
Challenges and risks associated with the technology sector.
Write at least 300-400 words, providing in-depth insights.
예시 1. 정부의 정책 지원과 기술 산업 성장
Government initiatives have significantly boosted the growth of the technology sector, acting as a catalyst for unprecedented innovation and development. In 2024, countries such as the United States and South Korea intensified their investments in cutting-edge fields like artificial intelligence (AI) and renewable energy technologies. These investments are not just sporadic measures but part of long-term strategies to secure global leadership in the technology sector. For instance, South Korea announced multi-billion-dollar funding initiatives targeting semiconductor production and AI research, while the United States expanded its CHIPS and Science Act programs to bolster domestic tech infrastructure. These advancements have made technology-focused ETFs integral to investment portfolios, particularly those aimed at innovation and sustainability. The alignment of public and private sector efforts has also provided a favorable environment for startups and tech enterprises, further accelerating growth in the ETF market.
예시 2. 헬스케어와 엣지 컴퓨팅의 부상
The rise of edge computing and AI in healthcare during 2024 has showcased how technological advancements are reshaping traditional industries in profound ways. By decentralizing data processing, edge computing has enabled real-time analytics in medical devices, enhancing patient care. Simultaneously, AI-driven healthcare innovations, such as precision diagnostics and personalized medicine, have gained significant traction among investors. For example, the integration of AI in wearable medical devices now allows continuous health monitoring, reducing the need for invasive procedures and hospital visits. These developments have made healthcare technology a pivotal theme within ETFs, as investors recognize the dual benefit of financial returns and societal impact. The potential of AI in revolutionizing drug discovery and streamlining clinical trials has further cemented its position as a hot topic in the ETF market.
예시 3. 지속 가능성과 기술 산업의 역할
Sustainability has emerged as another defining factor in the technology sector's growth. In 2024, technology companies have played a critical role in addressing global climate change challenges by advancing green technology and renewable energy solutions. Breakthroughs in solar panel efficiency, energy storage, and smart grid technology have not only reduced carbon footprints but also attracted significant ETF investments, particularly in November 2024. Countries and corporations alike have prioritized clean energy initiatives, with many committing to net-zero carbon emissions by 2050. ETFs focusing on green technology have seen record inflows, driven by investor confidence in the long-term profitability of sustainable innovations. Moreover, the fusion of AI and IoT in energy management systems has enabled unprecedented levels of efficiency, further reinforcing the technology sector's pivotal role in building a sustainable future.

<재생 에너지 산업>
Write a detailed explanation of why the renewable energy industry is highly promising in the ETF market. The article should be based on November 2024 news and cover the following aspects:
Government investments and their potential impact on the industry.
Current market trends driving demand for renewable energy.
Technological innovations and their role in enhancing industry growth.
Long-term sustainability and profitability as key factors for investors. Use a professional tone and provide at least 400 words, incorporating recent examples like major government policies, advancements in solar or wind technologies, and rising global energy demand.
예시 1. 정부 정책 관련
In November 2024, the United States unveiled a $10 billion renewable energy investment plan as part of its strategy to accelerate the adoption of wind and solar energy solutions. This significant funding initiative not only supports the construction of large-scale renewable energy projects but also provides subsidies for research and development in next-generation energy storage technologies. These measures align with the global ambition to achieve net-zero carbon emissions by 2050 and demonstrate the U.S. government's commitment to transitioning away from fossil fuels. Furthermore, South Korea announced a similar multi-billion-dollar initiative aimed at developing offshore wind farms and hydrogen fuel infrastructure, creating a robust framework for sustainable energy growth. On a broader scale, governments worldwide are intensifying their focus on clean energy transitions. The European Union, for instance, launched a green hydrogen initiative designed to reduce dependence on natural gas and coal, further driving investor confidence in ETFs tied to renewable energy companies. These coordinated efforts reflect a global consensus on the critical role renewable energy plays in economic and environmental stability.
예시 2. 시장 동향 관련
The global demand for renewable energy solutions has surged in response to escalating energy costs, supply chain disruptions, and the increasing urgency of climate change mitigation. In November 2024, leading solar panel manufacturers such as First Solar and LONGi Green Energy reported record profits due to unprecedented global demand. These developments have fueled significant ETF inflows, as investors recognize the strong growth potential of renewable energy markets. Wind energy has also gained substantial traction, with major offshore wind projects expanding rapidly in Asia and Europe. For example, China commissioned several offshore wind farms in 2024, generating over 10 gigawatts of renewable energy, while the United Kingdom's Dogger Bank Wind Farm is now supplying power to millions of homes. These developments underscore the lucrative opportunities within the wind energy sector and have led to increased investor participation in renewable energy ETFs. Additionally, the growing adoption of energy-efficient solutions in emerging markets highlights the global scope of this trend, reinforcing renewable energy as a cornerstone of future economic development.
예시 3. 기술 혁신 관련
Technological advancements in 2024 have significantly reduced the cost of renewable energy production, making it more competitive with traditional fossil fuels. For instance, next-generation solar panels developed this year have achieved efficiency rates 20% higher than traditional models, enabling greater energy capture even in low-sunlight conditions. These innovations have spurred investor interest in ETFs focused on renewable energy technologies. Similarly, advancements in wind turbine design, such as larger rotor blades and more durable materials, have increased energy output and reduced maintenance costs for wind farms. Battery storage technologies have also made substantial progress, with companies like Tesla and CATL introducing grid-scale solutions capable of storing renewable energy for extended periods. This innovation addresses one of the key challenges of renewable energy—intermittency—and has become a major driver of ETF growth. Furthermore, artificial intelligence and IoT integration in energy management systems have optimized energy distribution, reducing waste and enhancing grid efficiency. These breakthroughs highlight the transformative potential of technology in scaling renewable energy adoption and solidify its appeal to long-term investors.
예시 4. 지속 가능성과 투자 매력 관련
The renewable energy industry has emerged as a unique investment opportunity that addresses both environmental and financial concerns. By offering solutions to combat climate change, it appeals to socially responsible investors, while its profitability makes it a viable choice for traditional investment portfolios. In November 2024, renewable energy ETFs saw a record 15% increase in net inflows as sustainability-focused funds gained momentum. Major corporations have also embraced renewable energy as a central component of their ESG (Environmental, Social, and Governance) strategies, further boosting market confidence. For example, Amazon and Google announced partnerships with renewable energy providers to power their operations entirely with clean energy by 2030, showcasing the growing corporate demand for sustainable solutions. Meanwhile, the fusion of artificial intelligence and IoT in renewable energy management systems has enabled unprecedented levels of efficiency, further reinforcing the long-term viability of green investments. This dual-purpose appeal, balancing financial returns and environmental benefits, makes renewable energy ETFs a compelling choice for investors aiming to align their portfolios with the future of global energy.

"""

news_messages = [
    {
        "role": "system",
        "content": f"""Identify the industries recommended for investment in the news articles related to user input.
        Consider the news in {year}/{month} especially.
        Based on the news, recommend industries from the provided industry_list that are likely to benefit from {news_topic}.
        Consider both short-term opportunities and long-term growth potential when making your recommendations.
        Recommend as many as you think are appropriate, and describe the detail why you select those industries.
        Recommend at least 5 industries or more.
        plase explain each industry like this format: {news_example}"""
    },
    {
        "role": "user",
        "content": f"news topic:{news_topic}"
    }
]

response = client.chat.completions.create(
    model="llama-3.1-8b-instruct",
    messages=news_messages,
    temperature=0.7,
    max_tokens=1000
)

news_response= response.choices[0].message.content

industries_list=forstk['ids_nm'].unique().tolist()

prompt_template=PromptTemplate(
template=
"""
Please modify the answers from Perplexity AI to the following format. please using korean when answering

1. Industry name
   - Reason why this industry was chosen

2. Industry name
   - Reason why this industry was chosen

....


perplexity_ai_response: {perplexity_ai_response}
""",
)

client = AzureOpenAI(
        azure_endpoint = AZURE_ENDPOINT,
        api_key=AZURE_API_KEY,
        api_version='2024-02-15-preview',
        )
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "text" },
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {
            "role": "user",
            "content": prompt_template.format(
                perplexity_ai_response=news_response
            )
        }
    ]
)

news_reason= response.choices[0].message.content

news_response_json={
    'news_reason':news_reason
}

parser=CommaSeparatedListOutputParser()
prompt_template=PromptTemplate(
template=
"""
Create a list of the Korean industries from this recommendation data that I can select from the English industry list I provided.
You should only select from the following categories in the industry_list:
{industry_list}

Here is recommendation_data:{recommendation_data}

Please provide your recommendations in the following format:
{format_instructions}
""",
input_variables=["recommendation_data"],
partial_variables={"format_instructions": parser.get_format_instructions(), "industry_list": industries_list},
)

client = AzureOpenAI(
        azure_endpoint = AZURE_ENDPOINT,
        api_key=AZURE_API_KEY,
        api_version='2024-02-15-preview',
        )
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "text" },
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {
            "role": "user",
            "content": prompt_template.format(
                recommendation_data=news_reason
            )
        }
    ]
)

response=parser.invoke(response.choices[0].message.content)

industry_list=response

industry_list

# 뉴스 주제와 관련된 주식과 etf 추출
filtered_forstk = forstk[forstk['ids_nm'].isin(response)]

filtered_forstk['stk_etf_dit_cd'].value_counts()

# etf 리스트
forstk_etf_list=filtered_forstk[filtered_forstk['stk_etf_dit_cd']=='ETF']['tck_iem_cd'].to_list()
forstk_etf_list

# etf 리스트 개수
len(forstk_etf_list)

"""### 해당 주식 데이터를 이용해서 etf 리스트 뽑기"""

#필터1. 우선 리스트에 있는 주식을 가지고 있는 항목들을 필터링한다.
first_filter_holding = hold[hold['tck_iem_cd'].isin(filtered_forstk['tck_iem_cd'])]

# 두번째first_filter_holding['etf_tck_cd'] 필터. 해당 etf리스트 중 뽑아둔 주식/ETF가 10%이상인 주식들을 찾는다.
etf_list=first_filter_holding['etf_tck_cd'].unique().tolist()
filtered_etf_list=[]
for etf in etf_list:
  percentage=0.0
  for idx, row in first_filter_holding[first_filter_holding['etf_tck_cd']==etf].iterrows():
    percentage+=row['wht_pct']
  if percentage>=10:
    filtered_etf_list.append(etf)

# ETF list 추출
filtered_etf_list= list(set(filtered_etf_list + forstk_etf_list))

filtered_etf_list

"""## 4.1 ETF 리스트 검열
- 기준1. 안정성이 높은 것(최대낙폭Z점수)
- 기준2. 수익성이 높은 것(누적수익률Z점수, 정보비율Z점수)
- 기준3. 유동성이 높은 것(거래량, 거래대금)
- Z점수는 누락된 항목이 많아 직접 계산해서 추출한다.
"""

# ETF 검열을 위한 dataframe
etf_censor=pd.DataFrame(index=filtered_etf_list)
etf_censor.sort_index(inplace=True)
etf_censor.shape

# etf 이름 뒤의 공백 날리기
datepc['tck_iem_cd'] = datepc['tck_iem_cd'].str.strip()

"""### 4.1.1 유동성_누적 거래량, 거래대금의 평균"""

# trade_df에 누적 거래량, 거래대금의 평균값 저장
trade_df=datepc[['tck_iem_cd','acl_trd_qty','trd_cst']].groupby('tck_iem_cd').mean()

# filtered_etf_list에 있는 etf들만 추출
trade_df_index=list(filter(lambda x: x in filtered_etf_list, trade_df.index))

# trade_df에 filter 적용
trade_df=trade_df.loc[trade_df_index]
trade_df.columns=['acl_trd_qty_m','trd_cst_m']
trade_df.sort_index(inplace=True)
trade_df

"""### 4.2 수익성

### 4.2.1.1 누적수익율 Z점수
- 누적수익률 z점수: (누적수익률-평균누적수익률)/표준편차
- 다른 ETF와 비교한 값
"""

cumulative=datepc[['tck_iem_cd','bf_dd_cmp_ind_rt']]
cumulative['bf_dd_cmp_ind_rt']=np.log(1+cumulative['bf_dd_cmp_ind_rt']/100)
cumulative_1=cumulative.groupby('tck_iem_cd').sum()
cumulative_1['bf_dd_cmp_ind_rt']=np.exp(cumulative_1['bf_dd_cmp_ind_rt'])-1
cumulative_1

cumulative_mean=cumulative_1['bf_dd_cmp_ind_rt'].mean()
cumulative_std=cumulative_1['bf_dd_cmp_ind_rt'].std()

print(cumulative_mean)
print(cumulative_std)

cumulative_df=(cumulative_1['bf_dd_cmp_ind_rt']-cumulative_mean)/cumulative_std
cumulative_df

cumulative_z=cumulative_df.loc[list(filter(lambda x: x in filtered_etf_list, cumulative_df.index))]
cumulative_z.sort_index(inplace=True)
cumulative_z.name='cumulative_z'
cumulative_z

# Z 점수가 -1보다 작은 etf들 검열
delete_etf_list=cumulative_z[cumulative_z<-1].index.tolist()
delete_etf_list

filtered_etf_list_final = [etf for etf in filtered_etf_list if etf not in delete_etf_list]

len(filtered_etf_list_final)

"""### 4.1.2.2. 정보비율 Z점수(S&P500기준)"""

print(datepc['bse_dt'].min())

print(datepc['bse_dt'].max())

sp500 = yf.download('^GSPC', start='2024-05-27', end='2024-08-30')
sp500['returns']  = (sp500['Adj Close'] - sp500['Adj Close'].shift(1)) / sp500['Adj Close'].shift(1)

sp500=sp500.reset_index()

sp500['Date']= pd.to_datetime(sp500['Date'], format='%Y%m%d')
sp500['Date']= sp500['Date'].astype(str)

sp500['returns'].fillna(0, inplace=True)

datepc['bse_dt']= datepc['bse_dt'].astype(str)  # 문자열 변환
datepc['bse_dt']= pd.to_datetime(datepc['bse_dt'], format='%Y%m%d')
datepc['bse_dt']= datepc['bse_dt'].astype(str)

datepc

sp500.isna().sum()

sp500

def remove_time_column(df):
    df['Date'] = df['Date'].str.split(' ').str[0]
    return df

# 시간 부분을 제거한 데이터프레임 생성
sp500 = remove_time_column(sp500)

sp500

sp500.columns = ['Date', 'Adj_Close', 'Close', 'High', 'Low', 'Open', 'Volume', 'returns']

sp500

datepc['tck_iem_cd']=datepc['tck_iem_cd'].str.strip()
filtered_datepc = datepc[datepc['tck_iem_cd'].isin(filtered_etf_list_final)]

filtered_datepc.groupby('tck_iem_cd')['tck_iem_cd'].count()

merged_data = filtered_datepc.merge(sp500[['Date', 'returns']], left_on='bse_dt', right_on='Date', how='left')

# 수익률 차이를 계산합니다.
merged_data['return_diff'] = merged_data['bf_dd_cmp_ind_rt'] / 100 - merged_data['returns']

# ETF 별로 `return_diff`의 평균을 계산합니다.
information_ratios = merged_data.groupby('tck_iem_cd')['return_diff'].mean().tolist()

merged_data = datepc.merge(sp500[['Date', 'returns']], left_on='bse_dt', right_on='Date', how='left')

# 수익률 차이를 계산합니다.
merged_data['return_diff'] = merged_data['bf_dd_cmp_ind_rt'] / 100 - merged_data['returns']

# 각 ETF별로 `return_diff`의 평균을 계산하여 리스트에 추가합니다.
all_info_ratios = merged_data.groupby('tck_iem_cd')['return_diff'].mean().tolist()

mean_info=np.mean(all_info_ratios)
std_info=np.std(all_info_ratios)

print(mean_info)
print(std_info)
info_z_scores = [(cumulative_info - mean_info) / std_info for cumulative_info in information_ratios]

len(information_ratios)

len(info_z_scores)

len(filtered_etf_list_final)

# 정보비율 데이터프레임
info_df=pd.DataFrame(columns=['etf_list', 'info_z'])
info_df['etf_list']=filtered_etf_list_final
info_df['info_z']=info_z_scores
info_df=info_df.set_index('etf_list')
info_df.sort_index(inplace=True)
info_df

# Z 점수가 -1보다 작은 etf 리스트 검열
delete_etf_list=info_df[info_df['info_z']<-1].index.tolist()
delete_etf_list

filtered_etf_list_final = [etf for etf in filtered_etf_list_final if etf not in delete_etf_list]

len(filtered_etf_list_final)

"""### 4.1.3 안정성_최대낙폭z점수
특정 기간동안
(최고점 가격-최저점 가격)/최고점 가격*100
"""

datepc_ext=datepc[['tck_iem_cd','iem_hi_pr','iem_low_pr']]
datepc_ext.isna().sum()

# 0값을 아주 작은 값으로 대체
datepc_ext['iem_hi_pr'][datepc_ext['iem_hi_pr']==0]=0.0000001
datepc_ext.isna().sum()

datepc_ext['fall']=(datepc_ext['iem_hi_pr']-datepc_ext['iem_low_pr'])/datepc_ext['iem_hi_pr']
datepc_ext.isna().sum()

ext_fall=datepc_ext[['tck_iem_cd','fall']]
ext_fall_df=ext_fall.groupby('tck_iem_cd').mean()
ext_fall_mean=ext_fall_df['fall'].mean()
ext_fall_std=ext_fall_df['fall'].std()

print(ext_fall_mean)
print(ext_fall_std)

ext_fall_z=(ext_fall_df['fall']-ext_fall_mean)/ext_fall_std
ext_fall_z.name='fall_z'
ext_fall_z

# 최대낙폭Z점수 데이터프레임
fall_df=ext_fall_z.loc[list(filter(lambda x: x in filtered_etf_list, ext_fall_z.index))]
fall_df.sort_index(inplace=True)
fall_df

# z 점수가 1보다 큰 etf들 검열
delete_etf_list=fall_df[fall_df>1].index.tolist()
delete_etf_list

filtered_etf_list_final = [etf for etf in filtered_etf_list_final if etf not in delete_etf_list]

len(filtered_etf_list_final)

"""### 4.1.4. 배당금 리스트 추가하기"""

def high_div_list():
  """This function converts the dataframe of the price-to-dividend ratio for the filtered list of ETFs into JSON format and returns it. """
  filtered_div = div[div['etf_tck_cd'].isin(filtered_etf_list_final)]
  filtered_datepc = datepc[datepc['bf_dd_cmp_ind_pr'].between(-100, 100)]
  start_date=20230821
  end_date=20240821
  filtered_div=filtered_div[(filtered_div['ediv_dt'] >= start_date) & (filtered_div['ediv_dt'] <= end_date)]
  filtered_div = filtered_div.sort_values(by='etf_tck_cd')

  filtered_datepc=datepc[datepc['tck_iem_cd'].isin(filtered_datepc['tck_iem_cd'].unique())]
  filtered_datepc['bse_dt'] = pd.to_datetime(filtered_datepc['bse_dt'], format='%Y-%m-%d')

  start_date = '2023-08-21'
  end_date = '2024-08-21'
  filtered_datepc = filtered_datepc[(filtered_datepc['bse_dt'] >= start_date) & (filtered_datepc['bse_dt'] <= end_date)]

  avg_price_list=[]
  for etf in sorted(filtered_div['etf_tck_cd'].unique()):
    avg_price=filtered_datepc[filtered_datepc['tck_iem_cd']==etf]['iem_end_pr'].mean()
    avg_price_list.append(avg_price)

  grouped=filtered_div.groupby('etf_tck_cd')['aed_stkp_ddn_amt'].sum()
  grouped_df = grouped.reset_index()
  grouped_df['average'] = avg_price_list
  grouped_df['div_ratio']=grouped_df['aed_stkp_ddn_amt']/grouped_df['average']
  sorted_div_df=grouped_df.sort_values(by='div_ratio', ascending=False)
  sorted_div_df=sorted_div_df.drop(['average','aed_stkp_ddn_amt'], axis=1)

  return sorted_div_df

div_df=high_div_list()
div_df=div_df.set_index('etf_tck_cd')
div_df.sort_index(inplace=True)
div_df

"""### 4.1.5. 점수 취합하기
- 유동성: trade_df
- 수익성: cumulative_df, info_df
- 안정성: fall_df
- 배당금: div_df
"""

etf_censor=pd.concat([trade_df, cumulative_df, info_df, fall_df, div_df], axis=1)
etf_censor=etf_censor.loc[list(filter(lambda x: x in filtered_etf_list_final, etf_censor.index))]
etf_censor.dropna(inplace=True)
etf_censor

new_df=etf_censor.reset_index()
etf_censor_dic_data = new_df.to_dict(orient='records')
print(etf_censor_dic_data)

"""



##4.2 퍼플릭시티로 데이터 분석"""

client =  OpenAI(api_key=PERPLEXITY_API_KEY, base_url="https://api.perplexity.ai")

messages = [
    {
        "role": "system",
        "content": "You are an economic analyst"
    },
    {
        "role": "user",
        "content": f"""Based on the data I provide from a dataframe,
         analyze and recommend etf tickers. you need to recommend at least 5 tickers,
         but if the number of ETF tickers does not exceed 10,
         it is acceptable to recommend fewer than 5.
          Provide an in-depth assessment of their performance in terms of stability,
        growth potential, and income generation. dataframe: {etf_censor},

        The columns of dataframe I provide, 'acl_trd_qty_m' and 'trd_cst_m' are the measure of liquidity,
        mean the higher the measures are, the higher liquidity is.
        'bf_dd_cmp_ind_rt' is the measure of cumulative return rate, means
        the higher the measure is, the higher the return is.
        'info_z' is the measure of the similarity with S&P 500 movement, which we assume quite stable.
        it means the higher the measure is, the higher the similarity with S&P 500 movement.
        'fall_z' is the measure of volatility, means the lower the measure is, the lower the volatility is.
        Consider these features when analyzing.
        Notice that lower volatility means more stability.
        """
    }
]

response = client.chat.completions.create(
    model="llama-3.1-8b-instruct",
    messages=messages,
    temperature=0.7,
)

perplexity_response = response.choices[0].message.content

print(perplexity_response)

parser=CommaSeparatedListOutputParser()
prompt_template=PromptTemplate(
template=
"""
Create a list of ticker that was recommended in recommend data

Here is recommendation_data:{recommendation_data}

Please provide your recommendations in the following format:
{format_instructions}
""",
input_variables=["recommendation_data"],
partial_variables={"format_instructions": parser.get_format_instructions()},
)

client = AzureOpenAI(
        azure_endpoint = AZURE_ENDPOINT,
        api_key=AZURE_API_KEY,
        api_version='2024-02-15-preview',
        )
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "text" },
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {
            "role": "user",
            "content": prompt_template.format(
                recommendation_data=perplexity_response
            )
        }
    ]
)

recommended_ticker_list=parser.invoke(response.choices[0].message.content)

recommended_ticker_list

"""###  추천 etf 보고서 만들기"""

##holdings 구하기
hold['etf_tck_cd'] = hold['etf_tck_cd'].str.strip()
holding = hold[hold['etf_tck_cd'].isin(recommended_ticker_list)]

answer_format="""
example1
1. **ARKG ETF Overview**:
   - **Fund Objective**: ARKG is an actively managed ETF that seeks long-term growth of capital by investing primarily in domestic and foreign equity securities of companies across multiple sectors, including healthcare, that are relevant to the genomics revolution[5].
   - **Major Holdings**: The top holdings include Twist Bioscience Corp (TWST), CRISPR Therapeutics AG (CRSP), Recursion Pharmaceuticals Inc (RXRX), CareDx Inc (CDNA), and Intellia Therapeutics Inc (NTLA)[1][2][3].

2. **Asset Composition**:
   - **Healthcare**: The majority of ARKG's holdings are in the healthcare sector, specifically in biotechnology and medical diagnostics & research. Key companies include:
     - **Twist Bioscience Corp (TWST)**: A biotechnology company that designs, manufactures, and sells synthetic DNA.
     - **CRISPR Therapeutics AG (CRSP)**: A biotechnology company focused on developing gene editing therapies.
     - **Recursion Pharmaceuticals Inc (RXRX)**: A biotechnology company that uses machine learning to discover new drugs.
     - **CareDx Inc (CDNA)**: A medical diagnostics company that provides solutions for transplant patients.
     - **Intellia Therapeutics Inc (NTLA)**: A biotechnology company developing gene editing therapies[1][2][3].
   - **Health Information Services**: While not a primary focus, ARKG includes companies like Teladoc Health Inc (TDOC), which provides telemedicine services, though its holding percentage is minimal[1][3].

3. **Relevance to Specified Industries**:
   - **Health Information Services**: Minimal presence through Teladoc Health Inc (TDOC).
   - **Software - Application**: Not a primary focus, but some holdings like Tempus AI Inc (TEM) may have software components related to healthcare.

example2
1. ARKF ETF Overview**:
   - **Fund Objective**: ARKF is an actively managed ETF that seeks long-term growth of capital by investing primarily in domestic and foreign equity securities of companies across multiple sectors, including financial technology and innovation[5].
   - **Major Holdings**: The top holdings include PayPal Holdings Inc (PYPL), CrowdStrike Holdings Inc (CRWD), Zillow Group Inc (Z), and Teladoc Health Inc (TDOC)[1][2][3].

2. ARKF Asset Composition:
   - **Financial Technology**: The majority of ARKF's holdings are in financial technology and innovation. Key companies include:
     - **PayPal Holdings Inc (PYPL)**: A financial technology company that provides online payment systems.
     - **CrowdStrike Holdings Inc (CRWD)**: A cybersecurity company that provides cloud-delivered endpoint protection.
     - **Zillow Group Inc (Z)**: A real estate technology company that provides online real estate marketplace services.
   - **Health Information Services**: ARKF includes companies like Teladoc Health Inc (TDOC), which provides telemedicine services[1][3].

3. **Relevance to Specified Industries**:
   - **Health Information Services**: Presence through Teladoc Health Inc (TDOC).
   - **Security & Protection Services**: Presence through CrowdStrike Holdings Inc (CRWD).
   - **Software - Application**: Primary focus through companies like PayPal Holdings Inc (PYPL) and CrowdStrike Holdings Inc (CRWD).

"""

holding_perplexity_response=[]
for i in range(len(recommended_ticker_list)):
  ticker=recommended_ticker_list[i]
  ticker_holding=holding[holding['etf_tck_cd']==ticker]
  client =  OpenAI(api_key=PERPLEXITY_API_KEY, base_url="https://api.perplexity.ai")
  messages = [
      {
          "role": "system",
          "content": "You are an economic analyst"
      },
      {
          "role": "user",
          "content": f""""
          \I will provide an ETF asset composition DataFrame.
          For each ticker in the DataFrame, please provide an explanation of its asset composition,
          focusing on the major assets.
          Ensure that the explanation includes assets related to the industries
          listed in the {industry_list} as part of the overall composition.
          each ticker have to answer like {answer_format}

          dataframe:{ticker_holding}"""
      }
  ]
  response = client.chat.completions.create(
      model="llama-3.1-sonar-huge-128k-online",
      messages=messages,
      temperature=0.0,
  )
  first_perplexity_response = response.choices[0].message.content
  holding_perplexity_response.append(first_perplexity_response)

class ETF_recommend_result1(BaseModel):
  etf_explain1: str = Field(description="explaination about ticker")
  etf_asset1: str = Field(description="asset composition for ticker")
  etf_reason1: str = Field(description="reason why this ticker is recommended")

class ETF_recommend_result2(BaseModel):
  etf_explain2: str = Field(description="explaination about ticker")
  etf_asset2: str = Field(description="asset composition for ticker")
  etf_reason2: str = Field(description="reason why this ticker is recommended")

class ETF_recommend_result3(BaseModel):
  etf_explain3: str = Field(description="explaination about ticker")
  etf_asset3: str = Field(description="asset composition for ticker")
  etf_reason3: str = Field(description="reason why this ticker is recommended")

class ETF_recommend_result4(BaseModel):
  etf_explain4: str = Field(description="explaination about ticker")
  etf_asset4: str = Field(description="asset composition for ticker")
  etf_reason4: str = Field(description="reason why this ticker is recommended")

class ETF_recommend_result5(BaseModel):
  etf_explain5: str = Field(description="explaination about ticker")
  etf_asset5: str = Field(description="asset composition for ticker")
  etf_reason5: str = Field(description="reason why this ticker is recommended")

parser1= JsonOutputParser(pydantic_object=ETF_recommend_result1)
parser2= JsonOutputParser(pydantic_object=ETF_recommend_result2)
parser3= JsonOutputParser(pydantic_object=ETF_recommend_result3)
parser4= JsonOutputParser(pydantic_object=ETF_recommend_result4)
parser5= JsonOutputParser(pydantic_object=ETF_recommend_result5)

model=ChatOpenAI(model="gpt-4o", temperature=0, api_key=OPENAI_API_KEY)
prompt_template=PromptTemplate(
template="""

Please provide the following information for {ticker}:

Brief Description of {ticker}: Give a brief description of {ticker}.
{ticker} Asset Information: Provide the asset information for {ticker} based on the ETF list provided.
Give brief descriptions of those assets, about the industry it included.
Reason for ETF Recommendation: Explain why {ticker} is recommended based on the provided ETF recommendation list.
Since the provided information includes multiple ETFs, make sure to use only the details relevant to {ticker}.
Please answer Korean.
Also use the contents of {recommendation_data}, such as the reason why it selected those ETF in terms of stability,
growth potential, and income generation.
Use the contents of {news_reason}, such as the reason why the industry related to that ETF is recommended.

Please provide your recommendations in the following format:
{format_instructions}

Recommendation_data: {recommendation_data}
Asset_information:{asset_info}
""",
input_variables=["ticker", "asset_info", "format_instructions"],
partial_variables={ "recommendation_data":perplexity_response, "news_reason": news_reason},
)

client = AzureOpenAI(
        azure_endpoint = AZURE_ENDPOINT,
        api_key=AZURE_API_KEY,
        api_version='2024-02-15-preview',
        )

ticker=recommended_ticker_list[0]
data = etf_censor.loc[ticker]
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "json_object" },
    messages=[
        {"role": "system", "content": "You are a fund manager."},
        {
            "role": "user",
            "content": prompt_template.format(
                ticker=ticker,
                asset_info= holding_perplexity_response[0],
                format_instructions=parser1.get_format_instructions()
            )
        }
    ]
)
etf1_json = parser1.invoke(response.choices[0].message.content)
context={
      'ticker1': ticker,
      'cumulative_return1': data['acl_trd_qty_m'],
      'cumulative_z1': data['bf_dd_cmp_ind_rt'],
      'information_z1': data['info_z'],
      'drawdown_z1': data['fall_z'],
}
etf1_json.update(context)

ticker=recommended_ticker_list[1]
data = etf_censor.loc[ticker]
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "json_object" },
    messages=[
        {"role": "system", "content": "You are a fund manager."},
        {
            "role": "user",
            "content": prompt_template.format(
                ticker=ticker,
                asset_info= holding_perplexity_response[1],
                format_instructions=parser2.get_format_instructions()
            )
        }
    ]
)
etf2_json = parser2.invoke(response.choices[0].message.content)
context={
      'ticker2': ticker,
      'cumulative_return2': data['acl_trd_qty_m'],
      'cumulative_z2': data['bf_dd_cmp_ind_rt'],
      'information_z2': data['info_z'],
      'drawdown_z2': data['fall_z'],
}
etf2_json.update(context)

ticker=recommended_ticker_list[2]
data = etf_censor.loc[ticker]
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "json_object" },
    messages=[
        {"role": "system", "content": "You are a fund manager."},
        {
            "role": "user",
            "content": prompt_template.format(
                ticker=ticker,
                asset_info= holding_perplexity_response[2],
                format_instructions=parser3.get_format_instructions()
            )
        }
    ]
)
etf3_json = parser3.invoke(response.choices[0].message.content)
context={
      'ticker3': ticker,
      'cumulative_return3': data['acl_trd_qty_m'],
      'cumulative_z3': data['bf_dd_cmp_ind_rt'],
      'information_z3': data['info_z'],
      'drawdown_z3': data['fall_z'],
}
etf3_json.update(context)

ticker=recommended_ticker_list[3]
data = etf_censor.loc[ticker]
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "json_object" },
    messages=[
        {"role": "system", "content": "You are a fund manager."},
        {
            "role": "user",
            "content": prompt_template.format(
                ticker=ticker,
                asset_info= holding_perplexity_response[3],
                format_instructions=parser4.get_format_instructions()
            )
        }
    ]
)
etf4_json = parser4.invoke(response.choices[0].message.content)
context={
      'ticker4': ticker,
      'cumulative_return4': data['acl_trd_qty_m'],
      'cumulative_z4': data['bf_dd_cmp_ind_rt'],
      'information_z4': data['info_z'],
      'drawdown_z4': data['fall_z'],
}
etf4_json.update(context)

ticker=recommended_ticker_list[4]
data = etf_censor.loc[ticker]
response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "json_object" },
    messages=[
        {"role": "system", "content": "You are a fund manager."},
        {
            "role": "user",
            "content": prompt_template.format(
                ticker=ticker,
                asset_info= holding_perplexity_response[4],
                format_instructions=parser5.get_format_instructions()
            )
        }
    ]
)
etf5_json = parser5.invoke(response.choices[0].message.content)
context={
      'ticker5': ticker,
      'cumulative_return5': data['acl_trd_qty_m'],
      'cumulative_z5': data['bf_dd_cmp_ind_rt'],
      'information_z5': data['info_z'],
      'drawdown_z5': data['fall_z'],
}
etf5_json.update(context)

"""## 고객 특성별(나이, 자산) 데이터 가공"""

filtered_forstk['tck_iem_cd'] = filtered_forstk['tck_iem_cd'].str.strip()
cus['tck_iem_cd'] = cus['tck_iem_cd'].str.strip()

def find_age_code(age):
    if 0 <= age <= 29:
        return 21
    elif 30 <= age <= 39:
        return 22
    elif 40 <= age <= 49:
        return 23
    elif 50 <= age <= 59:
        return 24
    elif age >= 60:
        return 25
    else:
        return "Invalid age"

def find_income_code(amount):
    if amount < 30000000:
        return 31
    elif 30000000 <= amount < 100000000:
        return 32
    elif 100000000 <= amount < 1000000000:
        return 33
    elif amount >= 1000000000:
        return 34
    else:
        return "Invalid amount"

def customer_etf_list(customer_code):
    customer=cus[cus['tck_iem_cd'].isin(recommended_ticker_list)]
    customer_class=customer[customer['cus_cgr_mlf_cd']==customer_code]
    customer_class=customer_class[['tck_iem_cd','cus_cgr_act_cnt_rt','cus_cgr_ivs_rt']]
    customer_class_1=customer_class.groupby('tck_iem_cd').mean()
    return customer_class_1


"""이곳에 사용자 나이를 넣을 수 있습니다."""
age=50
customer_code=find_age_code(age)
age_df=customer_etf_list(customer_code)

"""이곳에 사용자 자산을 넣을 수 있습니다."""
wealth=1000000000
customer_code=find_income_code(wealth)
wealth_df=customer_etf_list(customer_code)
wealth_df

"""## 투자 비율 추천 서비스 만들기"""

client =  OpenAI(api_key=PERPLEXITY_API_KEY, base_url="https://api.perplexity.ai")

messages = [
    {
        "role": "system",
        "content": "You are an economic analyst"
    },
    {
        "role": "user",
        "content": f"""I am providing data frames processed by customer type. age_df contains data related to recommended ETFs for customers within specific age groups, while wealth_df includes data on customers based on their asset levels.

        The key columns in each data frame are as follows:

        CUS_CGR_ACT_CNT_RT: The proportion of accounts of this customer type relative to the total number of accounts.
        CUS_CGR_IVS_RT: The proportion of investment amount for this customer type relative to the total investment amount.
        explain which ticker is recommended to invest according to this dataframe
        age_df:{age_df}
        wealth_df:{wealth_df}
        """
    }
]

response = client.chat.completions.create(
    model="llama-3.1-8b-instruct",
    messages=messages,
    temperature=0.7,
)

customer_perplexity_response = response.choices[0].message.content

print(customer_perplexity_response)

investment_example="""
Example 1:
<Investment for 3-Month Period>

1. Conservative Investor
Recommended ETFs and Allocation:

AAPB (iShares 1-3 Year Credit Bond ETF): 50%
Provides stable returns with low risk through short-term bonds.
AIQ (iShares Global Inflation-Linked Bond ETF): 30%
Enhances portfolio stability with inflation-linked bonds.
XYLD (iShares Global Aggregate Bond ETF): 20%
Invests in global bonds, offering stability and diversification.
Summary:
AAPB and AIQ provide steady dividend yields with low risk, while XYLD contributes consistent dividend income through global bond investments.

2. Moderate Investor
Recommended ETFs and Allocation:

AAPB (iShares 1-3 Year Credit Bond ETF): 30%
Ensures stability through short-term bonds.
XYLD (iShares Global Aggregate Bond ETF): 20%
Reduces risk and secures steady dividends with global bond exposure.
AIQ (iShares Global Inflation-Linked Bond ETF): 20%
Aims for inflation protection and stable returns.
XVV (Invesco PowerShares 1-30 Laddered Treasury ETF): 15%
Complements stability with a range of treasury maturities.
XYLG (iShares 1-5 Year High Yield Corporate Bond ETF): 15%
Secures growth potential and dividend income through high-yield corporate bonds.
Summary:
This portfolio balances bond ETFs with high-yield corporate bonds, achieving both stability and dividend income while maintaining equilibrium between growth and defensive strategies.

3. Aggressive Investor
Recommended ETFs and Allocation:

XYLD (iShares Global Aggregate Bond ETF): 30%
Offers both stability and dividend income through global bonds.
XYLG (iShares 1-5 Year High Yield Corporate Bond ETF): 25%
Targets higher growth potential through high-yield corporate bonds.
AIQ (iShares Global Inflation-Linked Bond ETF): 20%
Maintains steady profitability and inflation protection.
AAPB (iShares 1-3 Year Credit Bond ETF): 15%
Provides stability through short-term credit bonds.
XVV (Invesco PowerShares 1-30 Laddered Treasury ETF): 10%
Diversifies risk with treasury bonds of various maturities.
Summary:
By emphasizing XYLD and XYLG, this portfolio maximizes dividend income while mitigating some risk with stable bond options, following a high-risk, high-return strategy.

Example 2:
<Investment for 3-Month Period>

1. Conservative Investor
Recommended ETFs and Allocation:

AAPB (iShares 1-3 Year Credit Bond ETF): 40%
Maximizes stability through short-term bonds.
AIQ (iShares Global Inflation-Linked Bond ETF): 30%
Provides inflation protection and stable returns.
XYLD (iShares Global Aggregate Bond ETF): 20%
Secures dividend income through global bonds.
XVV (Invesco PowerShares 1-30 Laddered Treasury ETF): 10%
Adds risk diversification and supplementary stability.
2. Moderate Investor
Recommended ETFs and Allocation:

AAPB (iShares 1-3 Year Credit Bond ETF): 30%
Lays a foundation for stable returns.
XYLD (iShares Global Aggregate Bond ETF): 25%
Provides both dividend income and stability.
AIQ (iShares Global Inflation-Linked Bond ETF): 20%
Strengthens portfolio balance and stability.
XYLG (iShares 1-5 Year High Yield Corporate Bond ETF): 15%
Captures growth opportunities through corporate bonds.
XVV (Invesco PowerShares 1-30 Laddered Treasury ETF): 10%
Complements the portfolio with stability.
3. Aggressive Investor
Recommended ETFs and Allocation:

XYLD (iShares Global Aggregate Bond ETF): 30%
Secures stable dividend income.
XYLG (iShares 1-5 Year High Yield Corporate Bond ETF): 25%
Maximizes growth and dividend income.
AAPB (iShares 1-3 Year Credit Bond ETF): 20%
Ensures liquidity and stability as a foundation.
AIQ (iShares Global Inflation-Linked Bond ETF): 15%
Provides inflation protection and portfolio balance.
XVV (Invesco PowerShares 1-30 Laddered Treasury ETF): 10%
Complements stability with sustainable returns.
Summary:
Dividend-focused ETFs like AAPB, AIQ, and XYLD are advantageous for short-term income generation, while growth-oriented ETFs like XYLG and XVV balance growth potential with stability.
"""

client = AzureOpenAI(
        azure_endpoint = AZURE_ENDPOINT,
        api_key=AZURE_API_KEY,
        api_version='2024-02-15-preview',
        )
prompt = f"""As an economic analyst, create tailored investment plans for the next 3 months, 6 months, 9 months, and 1 year based on the provided economic
conditions and customer profile data. Incorporate economic indicators such as {index_response} and {perplexity_response} from the Perplexity API,
 along with factors like interest rates, inflation, employment data, and stock market trends.

Use the customer data processed by type:
age_df: Contains ETF recommendations for specific age groups, showing popularity and investment amount across different age ranges.
wealth_df: Contains ETF recommendations based on customers' asset levels, showing preferences among higher-asset customers.
Incorporate the insights from {customer_perplexity_response} to reflect customer preferences and investment popularity based on age and wealth.
Using this information and the ETF recommendation list, propose strategies that align with the economic outlook and each investment timeframe.
For each plan, provide specific ETF allocations and explain how each ETF selection supports the customer’s risk profile and expected market conditions.

Please answer like this example format:
{investment_example}
 """

response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "text" },
    messages=[
        {"role": "system", "content": "You are an economic analyst."},
        {
            "role": "user",
            "content": prompt
        },
    ]
)

openai_response = response.choices[0].message.content

print(openai_response )

#유저 정보 입력
user_info="나는 20대 여성이야 나는 지금 계좌에 1000만원 정도 있어"

investment_recomend_example="""<Client Investment Strategy>

추천하는 투자 기간: 3개월

1. 보수적인 투자자
추천 ETF 및 할당 비율:

SCHD (Schwab U.S. Dividend Equity ETF): 35%
안정적인 배당 수익을 통해 낮은 변동성을 유지합니다.
VHT (Vanguard Health Care ETF): 35%
헬스케어 섹터의 안정성과 성장 가능성을 제공합니다.
AGG (iShares Core U.S. Aggregate Bond ETF): 30%
채권을 통해 시장 변동성을 줄이고 안정성을 확보합니다.
요약:
이 보수적인 포트폴리오는 SCHD와 VHT를 통해 안정적인 배당과 성장성을 추구하며, AGG를 추가해 리스크를 최소화합니다. 이는 중기적으로 자금을 안정적으로 운용하고자 하는 투자자에게 적합합니다.

2. 중립적인 투자자
추천 ETF 및 할당 비율:

SCHD (Schwab U.S. Dividend Equity ETF): 30%
배당 수익과 안정성을 동시에 제공합니다.
VHT (Vanguard Health Care ETF): 25%
헬스케어 분야에서 안정성과 성장을 균형 있게 추구합니다.
AGNG (iShares Aging Population ETF): 20%
인구 고령화 관련 산업에서 중장기적인 기회를 탐색합니다.
VOO (Vanguard S&P 500 ETF): 15%
대형주를 통해 시장 전반에 투자합니다.
QQQ (Invesco QQQ Trust): 10%
기술 섹터 중심의 성장 잠재력을 추가합니다.
요약:
중립적인 포트폴리오는 안정적인 배당과 성장 가능성을 조화롭게 결합하며, 기술 및 헬스케어 섹터에 일부 노출을 제공하여 성장의 기회를 추구합니다. 다양한 섹터에 분산 투자하여 균형 잡힌 성과를 기대할 수 있습니다.

3. 공격적인 투자자
추천 ETF 및 할당 비율:

QQQ (Invesco QQQ Trust): 40%
기술 중심의 높은 성장 가능성을 목표로 합니다.
VOO (Vanguard S&P 500 ETF): 30%
대형주 중심의 시장 성장을 활용합니다.
VHT (Vanguard Health Care ETF): 20%
안정적이면서도 지속 가능한 성장 섹터에 투자합니다.
ARKK (ARK Innovation ETF): 10%
혁신 기술 중심의 고위험, 고수익 잠재력을 더합니다.

전략이 귀하에게 적합한 이유:
중기적인 유연성
6개월은 단기보다는 더 높은 성장 가능성을 추구할 수 있으면서도 1년 이상 장기적인 자금 묶임에 대한 부담을 줄일 수 있는 적절한 기간입니다. 특히, 20대 여성이라면 학업, 커리어 변화, 또는 예상치 못한 자금 필요성이 있을 수 있으므로 너무 긴 투자 기간보다는 중기 투자로 유동성을 확보하는 것이 유리합니다.

리스크 관리와 성장의 균형
6개월 포트폴리오는 안정성과 성장 가능성을 적절히 조합하여, 보수적, 중간, 공격적 투자자 모두에게 균형 잡힌 선택지를 제공합니다. 특히, 6개월 동안은 시장 변동성을 어느 정도 흡수할 수 있는 시간이지만, 투자 손실 리스크가 장기보다 낮습니다.

이 전략을 통해 시장의 변동성에도 불구하고 성장 잠재력을 극대화하여 투자 목표를 달성할 수 있는 기회를 제공할 것입니다."""

client = AzureOpenAI(
        azure_endpoint = AZURE_ENDPOINT,
        api_key=AZURE_API_KEY,
        api_version='2024-02-15-preview',
        )

prompt = f"""Based on the user's profile and the investment strategy, choose the most suitable investment period strategy among the following options.
Since we don't know wether user's investment attitude, show all option for certain period. answer like this example {investment_recomend_example}
Please provide your answer in Korean. dont use * for answer. Answer as you recommend to the customer

User Profile: {user_info}
Investment Strategy: {openai_response}

Full Details of the Chosen Investment Strategy:
{{Detailed content of the chosen strategy}}

Reason Why This Strategy Is Suitable for the User:
{{Provide a detailed explanation of why this strategy fits the user's needs, considering their profile. For example, explain how the strategy aligns with the user's risk tolerance,
financial situation, interests, or any other relevant factors.}}
 """

response = client.chat.completions.create(
    model=deployment_name,
    response_format={ "type": "text" },
    messages=[
        {"role": "system", "content": "You are an economic analyst."},
        {
            "role": "user",
            "content": prompt
        },
    ]
)

openai_response = response.choices[0].message.content

print(openai_response)

invest_response_json={
    'investment_potofolio': openai_response
}

context_json=index_response_json
context_json.update(news_response_json)
context_json.update(etf1_json)
context_json.update(etf2_json)
context_json.update(etf3_json)
context_json.update(etf4_json)
context_json.update(etf5_json)
context_json.update(invest_response_json)

template=DocxTemplate('final_template.docx')
template.render(context_json)
template.save('final_result.docx')